document.addEventListener("DOMContentLoaded", () => {
    const input = document.getElementById("ejercicio");
    if (!input) return;

const listaEjercicios = [
    "Sentadilla",
    "Peso muerto",
    "Press de banca",
    "Zancadas",
    "Dominadas",
    "Curl de bíceps",
    "Press militar",
    "Plancha abdominal",
    "Remo con barra",
    "Hip thrust",
    "Burpees",
    "Swing con kettlebell",
    "Crunch oblicuo",
    "Extensiones de tríceps",
    "Flexiones de pecho",
    "Remo con mancuerna",
    "Press Arnold",
    "Step-ups",
    "Elevaciones laterales",
    "Peso muerto rumano",
 "Burpee a una pierna",
  "Burpee alternado",
  "Burpee alterno",
  "Burpee búlgaro",
  "Burpee cerrado",
  "Burpee con balón medicinal",
  "Burpee con banda",
  "Burpee con barra",
  "Burpee con kettlebell",
  "Burpee con mancuernas",
  "Burpee cruzado",
  "Burpee de pie",
  "Burpee declinado",
  "Burpee doble",
  "Burpee en TRX",
  "Burpee en banco plano",
  "Burpee en multipower",
  "Burpee en máquina",
  "Burpee en polea",
  "Burpee en suelo",
  "Burpee explosivo",
  "Burpee frontal",
  "Burpee goblet",
  "Burpee inclinado",
  "Burpee inverso",
  "Burpee isométrico",
  "Burpee lateral",
  "Burpee overhead",
  "Burpee paralelo",
  "Burpee profundo",
  "Burpee sentado",
  "Burpee sumo",
  "Burpee tras nuca",
  "Clean a una pierna",
  "Clean alternado",
  "Clean alterno",
  "Clean búlgaro",
  "Clean cerrado",
  "Clean con balón medicinal",
  "Clean con banda",
  "Clean con barra",
  "Clean con kettlebell",
  "Clean con mancuernas",
  "Clean cruzado",
  "Clean de pie",
  "Clean declinado",
  "Clean doble",
  "Clean en TRX",
  "Clean en banco plano",
  "Clean en multipower",
  "Clean en máquina",
  "Clean en polea",
  "Clean en suelo",
  "Clean explosivo",
  "Clean frontal",
  "Clean goblet",
  "Clean inclinado",
  "Clean inverso",
  "Clean isométrico",
  "Clean lateral",
  "Clean overhead",
  "Clean paralelo",
  "Clean profundo",
  "Clean sentado",
  "Clean sumo",
  "Clean tras nuca",
  "Crunch a una pierna",
  "Crunch alternado",
  "Crunch alterno",
  "Crunch búlgaro",
  "Crunch cerrado",
  "Crunch con balón medicinal",
  "Crunch con banda",
  "Crunch con barra",
  "Crunch con kettlebell",
  "Crunch con mancuernas",
  "Crunch cruzado",
  "Crunch de pie",
  "Crunch declinado",
  "Crunch doble",
  "Crunch en TRX",
  "Crunch en banco plano",
  "Crunch en multipower",
  "Crunch en máquina",
  "Crunch en polea",
  "Crunch en suelo",
  "Crunch explosivo",
  "Crunch frontal",
  "Crunch goblet",
  "Crunch inclinado",
  "Crunch inverso",
  "Crunch isométrico",
  "Crunch lateral",
  "Crunch overhead",
  "Crunch paralelo",
  "Crunch profundo",
  "Crunch sentado",
  "Crunch sumo",
  "Crunch tras nuca",
  "Curl de bíceps a una pierna",
  "Curl de bíceps alternado",
  "Curl de bíceps alterno",
  "Curl de bíceps búlgaro",
  "Curl de bíceps cerrado",
  "Curl de bíceps con balón medicinal",
  "Curl de bíceps con banda",
  "Curl de bíceps con barra",
  "Curl de bíceps con kettlebell",
  "Curl de bíceps con mancuernas",
  "Curl de bíceps cruzado",
  "Curl de bíceps de pie",
  "Curl de bíceps declinado",
  "Curl de bíceps doble",
  "Curl de bíceps en TRX",
  "Curl de bíceps en banco plano",
  "Curl de bíceps en multipower",
  "Curl de bíceps en máquina",
  "Curl de bíceps en polea",
  "Curl de bíceps en suelo",
  "Curl de bíceps explosivo",
  "Curl de bíceps frontal",
  "Curl de bíceps goblet",
  "Curl de bíceps inclinado",
  "Curl de bíceps inverso",
  "Curl de bíceps isométrico",
  "Curl de bíceps lateral",
  "Curl de bíceps overhead",
  "Curl de bíceps paralelo",
  "Curl de bíceps profundo",
  "Curl de bíceps sentado",
  "Curl de bíceps sumo",
  "Curl de bíceps tras nuca",
  "Curl femoral a una pierna",
  "Curl femoral alternado",
  "Curl femoral alterno",
  "Curl femoral búlgaro",
  "Curl femoral cerrado",
  "Curl femoral con balón medicinal",
  "Curl femoral con banda",
  "Curl femoral con barra",
  "Curl femoral con kettlebell",
  "Curl femoral con mancuernas",
  "Curl femoral cruzado",
  "Curl femoral de pie",
  "Curl femoral declinado",
  "Curl femoral doble",
  "Curl femoral en TRX",
  "Curl femoral en banco plano",
  "Curl femoral en multipower",
  "Curl femoral en máquina",
  "Curl femoral en polea",
  "Curl femoral en suelo",
  "Curl femoral explosivo",
  "Curl femoral frontal",
  "Curl femoral goblet",
  "Curl femoral inclinado",
  "Curl femoral inverso",
  "Curl femoral isométrico",
  "Curl femoral lateral",
  "Curl femoral overhead",
  "Curl femoral paralelo",
  "Curl femoral profundo",
  "Curl femoral sentado",
  "Curl femoral sumo",
  "Curl femoral tras nuca",
  "Dominadas a una pierna",
  "Dominadas alternado",
  "Dominadas alterno",
  "Dominadas búlgaro",
  "Dominadas cerrado",
  "Dominadas con balón medicinal",
  "Dominadas con banda",
  "Dominadas con barra",
  "Dominadas con kettlebell",
  "Dominadas con mancuernas",
  "Dominadas cruzado",
  "Dominadas de pie",
  "Dominadas declinado",
  "Dominadas doble",
  "Dominadas en TRX",
  "Dominadas en banco plano",
  "Dominadas en multipower",
  "Dominadas en máquina",
  "Dominadas en polea",
  "Dominadas en suelo",
  "Dominadas explosivo",
  "Dominadas frontal",
  "Dominadas goblet",
  "Dominadas inclinado",
  "Dominadas inverso",
  "Dominadas isométrico",
  "Dominadas lateral",
  "Dominadas overhead",
  "Dominadas paralelo",
  "Dominadas profundo",
  "Dominadas sentado",
  "Dominadas sumo",
  "Dominadas tras nuca",
  "Elevaciones laterales a una pierna",
  "Elevaciones laterales alternado",
  "Elevaciones laterales alterno",
  "Elevaciones laterales búlgaro",
  "Elevaciones laterales cerrado",
  "Elevaciones laterales con balón medicinal",
  "Elevaciones laterales con banda",
  "Elevaciones laterales con barra",
  "Elevaciones laterales con kettlebell",
  "Elevaciones laterales con mancuernas",
  "Elevaciones laterales cruzado",
  "Elevaciones laterales de pie",
  "Elevaciones laterales declinado",
  "Elevaciones laterales doble",
  "Elevaciones laterales en TRX",
  "Elevaciones laterales en banco plano",
  "Elevaciones laterales en multipower",
  "Elevaciones laterales en máquina",
  "Elevaciones laterales en polea",
  "Elevaciones laterales en suelo",
  "Elevaciones laterales explosivo",
  "Elevaciones laterales frontal",
  "Elevaciones laterales goblet",
  "Elevaciones laterales inclinado",
  "Elevaciones laterales inverso",
  "Elevaciones laterales isométrico",
  "Elevaciones laterales lateral",
  "Elevaciones laterales overhead",
  "Elevaciones laterales paralelo",
  "Elevaciones laterales profundo",
  "Elevaciones laterales sentado",
  "Elevaciones laterales sumo",
  "Elevaciones laterales tras nuca",
  "Extensión de piernas a una pierna",
  "Extensión de piernas alternado",
  "Extensión de piernas alterno",
  "Extensión de piernas búlgaro",
  "Extensión de piernas cerrado",
  "Extensión de piernas con balón medicinal",
  "Extensión de piernas con banda",
  "Extensión de piernas con barra",
  "Extensión de piernas con kettlebell",
  "Extensión de piernas con mancuernas",
  "Extensión de piernas cruzado",
  "Extensión de piernas de pie",
  "Extensión de piernas declinado",
  "Extensión de piernas doble",
  "Extensión de piernas en TRX",
  "Extensión de piernas en banco plano",
  "Extensión de piernas en multipower",
  "Extensión de piernas en máquina",
  "Extensión de piernas en polea",
  "Extensión de piernas en suelo",
  "Extensión de piernas explosivo",
  "Extensión de piernas frontal",
  "Extensión de piernas goblet",
  "Extensión de piernas inclinado",
  "Extensión de piernas inverso",
  "Extensión de piernas isométrico",
  "Extensión de piernas lateral",
  "Extensión de piernas overhead",
  "Extensión de piernas paralelo",
  "Extensión de piernas profundo",
  "Extensión de piernas sentado",
  "Extensión de piernas sumo",
  "Extensión de piernas tras nuca",
  "Extensión de tríceps a una pierna",
  "Extensión de tríceps alternado",
  "Extensión de tríceps alterno",
  "Extensión de tríceps búlgaro",
  "Extensión de tríceps cerrado",
  "Extensión de tríceps con balón medicinal",
  "Extensión de tríceps con banda",
  "Extensión de tríceps con barra",
  "Extensión de tríceps con kettlebell",
  "Extensión de tríceps con mancuernas",
  "Extensión de tríceps cruzado",
  "Extensión de tríceps de pie",
  "Extensión de tríceps declinado",
  "Extensión de tríceps doble",
  "Extensión de tríceps en TRX",
  "Extensión de tríceps en banco plano",
  "Extensión de tríceps en multipower",
  "Extensión de tríceps en máquina",
  "Extensión de tríceps en polea",
  "Extensión de tríceps en suelo",
  "Extensión de tríceps explosivo",
  "Extensión de tríceps frontal",
  "Extensión de tríceps goblet",
  "Extensión de tríceps inclinado",
  "Extensión de tríceps inverso",
  "Extensión de tríceps isométrico",
  "Extensión de tríceps lateral",
  "Extensión de tríceps overhead",
  "Extensión de tríceps paralelo",
  "Extensión de tríceps profundo",
  "Extensión de tríceps sentado",
  "Extensión de tríceps sumo",
  "Extensión de tríceps tras nuca",
  "Flexiones a una pierna",
  "Flexiones alternado",
  "Flexiones alterno",
  "Flexiones búlgaro",
  "Flexiones cerrado",
  "Flexiones con balón medicinal",
  "Flexiones con banda",
  "Flexiones con barra",
  "Flexiones con kettlebell",
  "Flexiones con mancuernas",
  "Flexiones cruzado",
  "Flexiones de pie",
  "Flexiones declinado",
  "Flexiones doble",
  "Flexiones en TRX",
  "Flexiones en banco plano",
  "Flexiones en multipower",
  "Flexiones en máquina",
  "Flexiones en polea",
  "Flexiones en suelo",
  "Flexiones explosivo",
  "Flexiones frontal",
  "Flexiones goblet",
  "Flexiones inclinado",
  "Flexiones inverso",
  "Flexiones isométrico",
  "Flexiones lateral",
  "Flexiones overhead",
  "Flexiones paralelo",
  "Flexiones profundo",
  "Flexiones sentado",
  "Flexiones sumo",
  "Flexiones tras nuca",
  "Hip thrust a una pierna",
  "Hip thrust alternado",
  "Hip thrust alterno",
  "Hip thrust búlgaro",
  "Hip thrust cerrado",
  "Hip thrust con balón medicinal",
  "Hip thrust con banda",
  "Hip thrust con barra",
  "Hip thrust con kettlebell",
  "Hip thrust con mancuernas",
  "Hip thrust cruzado",
  "Hip thrust de pie",
  "Hip thrust declinado",
  "Hip thrust doble",
  "Hip thrust en TRX",
  "Hip thrust en banco plano",
  "Hip thrust en multipower",
  "Hip thrust en máquina",
  "Hip thrust en polea",
  "Hip thrust en suelo",
  "Hip thrust explosivo",
  "Hip thrust frontal",
  "Hip thrust goblet",
  "Hip thrust inclinado",
  "Hip thrust inverso",
  "Hip thrust isométrico",
  "Hip thrust lateral",
  "Hip thrust overhead",
  "Hip thrust paralelo",
  "Hip thrust profundo",
  "Hip thrust sentado",
  "Hip thrust sumo",
  "Hip thrust tras nuca",
  "Mountain climbers a una pierna",
  "Mountain climbers alternado",
  "Mountain climbers alterno",
  "Mountain climbers búlgaro",
  "Mountain climbers cerrado",
  "Mountain climbers con balón medicinal",
  "Mountain climbers con banda",
  "Mountain climbers con barra",
  "Mountain climbers con kettlebell",
  "Mountain climbers con mancuernas",
  "Mountain climbers cruzado",
  "Mountain climbers de pie",
  "Mountain climbers declinado",
  "Mountain climbers doble",
  "Mountain climbers en TRX",
  "Mountain climbers en banco plano",
  "Mountain climbers en multipower",
  "Mountain climbers en máquina",
  "Mountain climbers en polea",
  "Mountain climbers en suelo",
  "Mountain climbers explosivo",
  "Mountain climbers frontal",
  "Mountain climbers goblet",
  "Mountain climbers inclinado",
  "Mountain climbers inverso",
  "Mountain climbers isométrico",
  "Mountain climbers lateral",
  "Mountain climbers overhead",
  "Mountain climbers paralelo",
  "Mountain climbers profundo",
  "Mountain climbers sentado",
  "Mountain climbers sumo",
  "Mountain climbers tras nuca",
  "Peso muerto a una pierna",
  "Peso muerto alternado",
  "Peso muerto alterno",
  "Peso muerto búlgaro",
  "Peso muerto cerrado",
  "Peso muerto con balón medicinal",
  "Peso muerto con banda",
  "Peso muerto con barra",
  "Peso muerto con kettlebell",
  "Peso muerto con mancuernas",
  "Peso muerto cruzado",
  "Peso muerto de pie",
  "Peso muerto declinado",
  "Peso muerto doble",
  "Peso muerto en TRX",
  "Peso muerto en banco plano",
  "Peso muerto en multipower",
  "Peso muerto en máquina",
  "Peso muerto en polea",
  "Peso muerto en suelo",
  "Peso muerto explosivo",
  "Peso muerto frontal",
  "Peso muerto goblet",
  "Peso muerto inclinado",
  "Peso muerto inverso",
  "Peso muerto isométrico",
  "Peso muerto lateral",
  "Peso muerto overhead",
  "Peso muerto paralelo",
  "Peso muerto profundo",
  "Peso muerto sentado",
  "Peso muerto sumo",
  "Peso muerto tras nuca",
  "Plancha a una pierna",
  "Plancha alternado",
  "Plancha alterno",
  "Plancha búlgaro",
  "Plancha cerrado",
  "Plancha con balón medicinal",
  "Plancha con banda",
  "Plancha con barra",
  "Plancha con kettlebell",
  "Plancha con mancuernas",
  "Plancha cruzado",
  "Plancha de pie",
  "Plancha declinado",
  "Plancha doble",
  "Plancha en TRX",
  "Plancha en banco plano",
  "Plancha en multipower",
  "Plancha en máquina",
  "Plancha en polea",
  "Plancha en suelo",
  "Plancha explosivo",
  "Plancha frontal",
  "Plancha goblet",
  "Plancha inclinado",
  "Plancha inverso",
  "Plancha isométrico",
  "Plancha lateral",
  "Plancha overhead",
  "Plancha paralelo",
  "Plancha profundo",
  "Plancha sentado",
  "Plancha sumo",
  "Plancha tras nuca",
  "Press de banca a una pierna",
  "Press de banca alternado",
  "Press de banca alterno",
  "Press de banca búlgaro",
  "Press de banca cerrado",
  "Press de banca con balón medicinal",
  "Press de banca con banda",
  "Press de banca con barra",
  "Press de banca con kettlebell",
  "Press de banca con mancuernas",
  "Press de banca cruzado",
  "Press de banca de pie",
  "Press de banca declinado",
  "Press de banca doble",
  "Press de banca en TRX",
  "Press de banca en banco plano",
  "Press de banca en multipower",
  "Press de banca en máquina",
  "Press de banca en polea",
  "Press de banca en suelo",
  "Press de banca explosivo",
  "Press de banca frontal",
  "Press de banca goblet",
  "Press de banca inclinado",
  "Press de banca inverso",
  "Press de banca isométrico",
  "Press de banca lateral",
  "Press de banca overhead",
  "Press de banca paralelo",
  "Press de banca profundo",
  "Press de banca sentado",
  "Press de banca sumo",
  "Press de banca tras nuca",
  "Press militar a una pierna",
  "Press militar alternado",
  "Press militar alterno",
  "Press militar búlgaro",
  "Press militar cerrado",
  "Press militar con balón medicinal",
  "Press militar con banda",
  "Press militar con barra",
  "Press militar con kettlebell",
  "Press militar con mancuernas",
  "Press militar cruzado",
  "Press militar de pie",
  "Press militar declinado",
  "Press militar doble",
  "Press militar en TRX",
  "Press militar en banco plano",
  "Press militar en multipower",
  "Press militar en máquina",
  "Press militar en polea",
  "Press militar en suelo",
  "Press militar explosivo",
  "Press militar frontal",
  "Press militar goblet",
  "Press militar inclinado",
  "Press militar inverso",
  "Press militar isométrico",
  "Press militar lateral",
  "Press militar overhead",
  "Press militar paralelo",
  "Press militar profundo",
  "Press militar sentado",
  "Press militar sumo",
  "Press militar tras nuca",
  "Remo a una pierna",
  "Remo alternado",
  "Remo alterno",
  "Remo búlgaro",
  "Remo cerrado",
  "Remo con balón medicinal",
  "Remo con banda",
  "Remo con barra",
  "Remo con kettlebell",
  "Remo con mancuernas",
  "Remo cruzado",
  "Remo de pie",
  "Remo declinado",
  "Remo doble",
  "Remo en TRX",
  "Remo en banco plano",
  "Remo en multipower",
  "Remo en máquina",
  "Remo en polea",
  "Remo en suelo",
  "Remo explosivo",
  "Remo frontal",
  "Remo goblet",
  "Remo inclinado",
  "Remo inverso",
  "Remo isométrico",
  "Remo lateral",
  "Remo overhead",
  "Remo paralelo",
  "Remo profundo",
  "Remo sentado",
  "Remo sumo",
  "Remo tras nuca",
  "Saltar la cuerda a una pierna",
  "Saltar la cuerda alternado",
  "Saltar la cuerda alterno",
  "Saltar la cuerda búlgaro",
  "Saltar la cuerda cerrado",
  "Saltar la cuerda con balón medicinal",
  "Saltar la cuerda con banda",
  "Saltar la cuerda con barra",
  "Saltar la cuerda con kettlebell",
  "Saltar la cuerda con mancuernas",
  "Saltar la cuerda cruzado",
  "Saltar la cuerda de pie",
  "Saltar la cuerda declinado",
  "Saltar la cuerda doble",
  "Saltar la cuerda en TRX",
  "Saltar la cuerda en banco plano",
  "Saltar la cuerda en multipower",
  "Saltar la cuerda en máquina",
  "Saltar la cuerda en polea",
  "Saltar la cuerda en suelo",
  "Saltar la cuerda explosivo",
  "Saltar la cuerda frontal",
  "Saltar la cuerda goblet",
  "Saltar la cuerda inclinado",
  "Saltar la cuerda inverso",
  "Saltar la cuerda isométrico",
  "Saltar la cuerda lateral",
  "Saltar la cuerda overhead",
  "Saltar la cuerda paralelo",
  "Saltar la cuerda profundo",
  "Saltar la cuerda sentado",
  "Saltar la cuerda sumo",
  "Saltar la cuerda tras nuca",
  "Sentadilla a una pierna",
  "Sentadilla alternado",
  "Sentadilla alterno",
  "Sentadilla búlgaro",
  "Sentadilla cerrado",
  "Sentadilla con balón medicinal",
  "Sentadilla con banda",
  "Sentadilla con barra",
  "Sentadilla con kettlebell",
  "Sentadilla con mancuernas",
  "Sentadilla cruzado",
  "Sentadilla de pie",
  "Sentadilla declinado",
  "Sentadilla doble",
  "Sentadilla en TRX",
  "Sentadilla en banco plano",
  "Sentadilla en multipower",
  "Sentadilla en máquina",
  "Sentadilla en polea",
  "Sentadilla en suelo",
  "Sentadilla explosivo",
  "Sentadilla frontal",
  "Sentadilla goblet",
  "Sentadilla inclinado",
  "Sentadilla inverso",
  "Sentadilla isométrico",
  "Sentadilla lateral",
  "Sentadilla overhead",
  "Sentadilla paralelo",
  "Sentadilla profundo",
  "Sentadilla sentado",
  "Sentadilla sumo",
  "Sentadilla tras nuca",
  "Snatch a una pierna",
  "Snatch alternado",
  "Snatch alterno",
  "Snatch búlgaro",
  "Snatch cerrado",
  "Snatch con balón medicinal",
  "Snatch con banda",
  "Snatch con barra",
  "Snatch con kettlebell",
  "Snatch con mancuernas",
  "Snatch cruzado",
  "Snatch de pie",
  "Snatch declinado",
  "Snatch doble",
  "Snatch en TRX",
  "Snatch en banco plano",
  "Snatch en multipower",
  "Snatch en máquina",
  "Snatch en polea",
  "Snatch en suelo",
  "Snatch explosivo",
  "Snatch frontal",
  "Snatch goblet",
  "Snatch inclinado",
  "Snatch inverso",
  "Snatch isométrico",
  "Snatch lateral",
  "Snatch overhead",
  "Snatch paralelo",
  "Snatch profundo",
  "Snatch sentado",
  "Snatch sumo",
  "Snatch tras nuca",
  "Step-up a una pierna",
  "Step-up alternado",
  "Step-up alterno",
  "Step-up búlgaro",
  "Step-up cerrado",
  "Step-up con balón medicinal",
  "Step-up con banda",
  "Step-up con barra",
  "Step-up con kettlebell",
  "Step-up con mancuernas",
  "Step-up cruzado",
  "Step-up de pie",
  "Step-up declinado",
  "Step-up doble",
  "Step-up en TRX",
  "Step-up en banco plano",
  "Step-up en multipower",
  "Step-up en máquina",
  "Step-up en polea",
  "Step-up en suelo",
  "Step-up explosivo",
  "Step-up frontal",
  "Step-up goblet",
  "Step-up inclinado",
  "Step-up inverso",
  "Step-up isométrico",
  "Step-up lateral",
  "Step-up overhead",
  "Step-up paralelo",
  "Step-up profundo",
  "Step-up sentado",
  "Step-up sumo",
  "Step-up tras nuca",
  "Swing a una pierna",
  "Swing alternado",
  "Swing alterno",
  "Swing búlgaro",
  "Swing cerrado",
  "Swing con balón medicinal",
  "Swing con banda",
  "Swing con barra",
  "Swing con kettlebell",
  "Swing con mancuernas",
  "Swing cruzado",
  "Swing de pie",
  "Swing declinado",
  "Swing doble",
  "Swing en TRX",
  "Swing en banco plano",
  "Swing en multipower",
  "Swing en máquina",
  "Swing en polea",
  "Swing en suelo",
  "Swing explosivo",
  "Swing frontal",
  "Swing goblet",
  "Swing inclinado",
  "Swing inverso",
  "Swing isométrico",
  "Swing lateral",
  "Swing overhead",
  "Swing paralelo",
  "Swing profundo",
  "Swing sentado",
  "Swing sumo",
  "Swing tras nuca",
  "Zancadas a una pierna",
  "Zancadas alternado",
  "Zancadas alterno",
  "Zancadas búlgaro",
  "Zancadas cerrado",
  "Zancadas con balón medicinal",
  "Zancadas con banda",
  "Zancadas con barra",
  "Zancadas con kettlebell",
  "Zancadas con mancuernas",
  "Zancadas cruzado",
  "Zancadas de pie",
  "Zancadas declinado",
  "Zancadas doble",
  "Zancadas en TRX",
  "Zancadas en banco plano",
  "Zancadas en multipower",
  "Zancadas en máquina",
  "Zancadas en polea",
  "Zancadas en suelo",
  "Zancadas explosivo",
  "Zancadas frontal",
  "Zancadas goblet",
  "Zancadas inclinado",
  "Zancadas inverso",
  "Zancadas isométrico",
  "Zancadas lateral",
  "Zancadas overhead",
  "Zancadas paralelo",
  "Zancadas profundo",
  "Zancadas sentado",
  "Zancadas sumo",
  "Zancadas tras nuca",
  "Ab roll",
  "Aperturas en banco inclinado",
  "Aperturas en banco plano",
  "Battle ropes",
  "Bicicleta abdominal",
  "Bicicleta fija",
  "Burpees",
  "Caminata en cinta",
  "Crunch abdominal",
  "Crunch oblicuo",
  "Curl alterno con mancuernas",
  "Curl con barra",
  "Curl con barra Z",
  "Curl con cable",
  "Curl concentración",
  "Curl en banco Scott",
  "Curl en banco inclinado",
  "Curl en polea baja",
  "Curl femoral",
  "Curl martillo",
  "Curl spider",
  "Dominadas",
  "Elevaciones frontales",
  "Elevaciones laterales",
  "Elevación de piernas",
  "Elevación de talones",
  "Elevación en máquina",
  "Encogimientos",
  "Extensión con mancuerna",
  "Extensión de piernas",
  "Extensión en polea",
  "Extensión sentado",
  "Face pull",
  "Flexiones de pecho",
  "Fondos en paralelas",
  "Fondos entre bancos",
  "Hip thrust",
  "Jalón al pecho",
  "Jalón tras nuca",
  "Jumping jacks",
  "Kickbacks",
  "Mountain climbers",
  "Patada de tríceps",
  "Peso muerto rumano",
  "Plancha",
  "Plancha lateral",
  "Prensa de piernas",
  "Press Arnold",
  "Press cerrado",
  "Press con banda",
  "Press con cable",
  "Press con mancuernas",
  "Press de banca plano",
  "Press declinado",
  "Press en máquina",
  "Press francés",
  "Press inclinado con mancuernas",
  "Press militar",
  "Press tras nuca",
  "Pull over con mancuernas",
  "Pájaros",
  "Remo T-bar",
  "Remo al mentón",
  "Remo con barra",
  "Remo con mancuerna",
  "Remo en máquina",
  "Remo en polea baja",
  "Remo ergómetro",
  "Running en el lugar",
  "Russian twist",
  "Saltar la cuerda",
  "Sentadilla frontal",
  "Sentadilla hack",
  "Sentadilla trasera",
  "Ski erg",
  "Step-ups rápidos",
  "Toques de talones",
  "Tríceps con cuerda",
  "Tríceps en banco",
  "Zancadas caminando",
  "Aperturas",
  "Aperturas a una pierna",
  "Aperturas asistido",
  "Aperturas con TRX",
  "Aperturas con agarre cerrado",
  "Aperturas con balón medicinal",
  "Aperturas con banda elástica",
  "Aperturas con barra",
  "Aperturas con mancuernas",
  "Aperturas en banco Scott",
  "Aperturas en banco inclinado",
  "Aperturas en banco plano",
  "Aperturas en banco romano",
  "Aperturas en multipower",
  "Aperturas en máquina",
  "Aperturas en polea",
  "Aperturas en suelo",
  "Aperturas explosivo",
  "Aperturas isométrico",
  "Aperturas libre",
  "Aperturas modificado",
  "Burpees",
  "Burpees a una pierna",
  "Burpees asistido",
  "Burpees con TRX",
  "Burpees con agarre cerrado",
  "Burpees con balón medicinal",
  "Burpees con banda elástica",
  "Burpees con barra",
  "Burpees con mancuernas",
  "Burpees en banco Scott",
  "Burpees en banco inclinado",
  "Burpees en banco plano",
  "Burpees en banco romano",
  "Burpees en multipower",
  "Burpees en máquina",
  "Burpees en polea",
  "Burpees en suelo",
  "Burpees explosivo",
  "Burpees isométrico",
  "Burpees libre",
  "Burpees modificado",
  "Crunch",
  "Crunch a una pierna",
  "Crunch asistido",
  "Crunch con TRX",
  "Crunch con agarre cerrado",
  "Crunch con balón medicinal",
  "Crunch con banda elástica",
  "Crunch con barra",
  "Crunch con mancuernas",
  "Crunch en banco Scott",
  "Crunch en banco inclinado",
  "Crunch en banco plano",
  "Crunch en banco romano",
  "Crunch en multipower",
  "Crunch en máquina",
  "Crunch en polea",
  "Crunch en suelo",
  "Crunch explosivo",
  "Crunch isométrico",
  "Crunch libre",
  "Crunch modificado",
  "Curl de bíceps",
  "Curl de bíceps a una pierna",
  "Curl de bíceps asistido",
  "Curl de bíceps con TRX",
  "Curl de bíceps con agarre cerrado",
  "Curl de bíceps con balón medicinal",
  "Curl de bíceps con banda elástica",
  "Curl de bíceps con barra",
  "Curl de bíceps con mancuernas",
  "Curl de bíceps en banco Scott",
  "Curl de bíceps en banco inclinado",
  "Curl de bíceps en banco plano",
  "Curl de bíceps en banco romano",
  "Curl de bíceps en multipower",
  "Curl de bíceps en máquina",
  "Curl de bíceps en polea",
  "Curl de bíceps en suelo",
  "Curl de bíceps explosivo",
  "Curl de bíceps isométrico",
  "Curl de bíceps libre",
  "Curl de bíceps modificado",
  "Dominadas",
  "Dominadas a una pierna",
  "Dominadas asistido",
  "Dominadas con TRX",
  "Dominadas con agarre cerrado",
  "Dominadas con balón medicinal",
  "Dominadas con banda elástica",
  "Dominadas con barra",
  "Dominadas con mancuernas",
  "Dominadas en banco Scott",
  "Dominadas en banco inclinado",
  "Dominadas en banco plano",
  "Dominadas en banco romano",
  "Dominadas en multipower",
  "Dominadas en máquina",
  "Dominadas en polea",
  "Dominadas en suelo",
  "Dominadas explosivo",
  "Dominadas isométrico",
  "Dominadas libre",
  "Dominadas modificado",
  "Elevaciones",
  "Elevaciones a una pierna",
  "Elevaciones asistido",
  "Elevaciones con TRX",
  "Elevaciones con agarre cerrado",
  "Elevaciones con balón medicinal",
  "Elevaciones con banda elástica",
  "Elevaciones con barra",
  "Elevaciones con mancuernas",
  "Elevaciones de piernas",
  "Elevaciones de piernas a una pierna",
  "Elevaciones de piernas asistido",
  "Elevaciones de piernas con TRX",
  "Elevaciones de piernas con agarre cerrado",
  "Elevaciones de piernas con balón medicinal",
  "Elevaciones de piernas con banda elástica",
  "Elevaciones de piernas con barra",
  "Elevaciones de piernas con mancuernas",
  "Elevaciones de piernas en banco Scott",
  "Elevaciones de piernas en banco inclinado",
  "Elevaciones de piernas en banco plano",
  "Elevaciones de piernas en banco romano",
  "Elevaciones de piernas en multipower",
  "Elevaciones de piernas en máquina",
  "Elevaciones de piernas en polea",
  "Elevaciones de piernas en suelo",
  "Elevaciones de piernas explosivo",
  "Elevaciones de piernas isométrico",
  "Elevaciones de piernas libre",
  "Elevaciones de piernas modificado",
  "Elevaciones en banco Scott",
  "Elevaciones en banco inclinado",
  "Elevaciones en banco plano",
  "Elevaciones en banco romano",
  "Elevaciones en multipower",
  "Elevaciones en máquina",
  "Elevaciones en polea",
  "Elevaciones en suelo",
  "Elevaciones explosivo",
  "Elevaciones isométrico",
  "Elevaciones libre",
  "Elevaciones modificado",
  "Encogimientos",
  "Encogimientos a una pierna",
  "Encogimientos asistido",
  "Encogimientos con TRX",
  "Encogimientos con agarre cerrado",
  "Encogimientos con balón medicinal",
  "Encogimientos con banda elástica",
  "Encogimientos con barra",
  "Encogimientos con mancuernas",
  "Encogimientos en banco Scott",
  "Encogimientos en banco inclinado",
  "Encogimientos en banco plano",
  "Encogimientos en banco romano",
  "Encogimientos en multipower",
  "Encogimientos en máquina",
  "Encogimientos en polea",
  "Encogimientos en suelo",
  "Encogimientos explosivo",
  "Encogimientos isométrico",
  "Encogimientos libre",
  "Encogimientos modificado",
  "Extensión de tríceps",
  "Extensión de tríceps a una pierna",
  "Extensión de tríceps asistido",
  "Extensión de tríceps con TRX",
  "Extensión de tríceps con agarre cerrado",
  "Extensión de tríceps con balón medicinal",
  "Extensión de tríceps con banda elástica",
  "Extensión de tríceps con barra",
  "Extensión de tríceps con mancuernas",
  "Extensión de tríceps en banco Scott",
  "Extensión de tríceps en banco inclinado",
  "Extensión de tríceps en banco plano",
  "Extensión de tríceps en banco romano",
  "Extensión de tríceps en multipower",
  "Extensión de tríceps en máquina",
  "Extensión de tríceps en polea",
  "Extensión de tríceps en suelo",
  "Extensión de tríceps explosivo",
  "Extensión de tríceps isométrico",
  "Extensión de tríceps libre",
  "Extensión de tríceps modificado",
  "Flexiones",
  "Flexiones a una pierna",
  "Flexiones asistido",
  "Flexiones con TRX",
  "Flexiones con agarre cerrado",
  "Flexiones con balón medicinal",
  "Flexiones con banda elástica",
  "Flexiones con barra",
  "Flexiones con mancuernas",
  "Flexiones en banco Scott",
  "Flexiones en banco inclinado",
  "Flexiones en banco plano",
  "Flexiones en banco romano",
  "Flexiones en multipower",
  "Flexiones en máquina",
  "Flexiones en polea",
  "Flexiones en suelo",
  "Flexiones explosivo",
  "Flexiones isométrico",
  "Flexiones libre",
  "Flexiones modificado",
  "Fondos",
  "Fondos a una pierna",
  "Fondos asistido",
  "Fondos con TRX",
  "Fondos con agarre cerrado",
  "Fondos con balón medicinal",
  "Fondos con banda elástica",
  "Fondos con barra",
  "Fondos con mancuernas",
  "Fondos en banco Scott",
  "Fondos en banco inclinado",
  "Fondos en banco plano",
  "Fondos en banco romano",
  "Fondos en multipower",
  "Fondos en máquina",
  "Fondos en polea",
  "Fondos en suelo",
  "Fondos explosivo",
  "Fondos isométrico",
  "Fondos libre",
  "Fondos modificado",
  "Jalón",
  "Jalón a una pierna",
  "Jalón asistido",
  "Jalón con TRX",
  "Jalón con agarre cerrado",
  "Jalón con balón medicinal",
  "Jalón con banda elástica",
  "Jalón con barra",
  "Jalón con mancuernas",
  "Jalón en banco Scott",
  "Jalón en banco inclinado",
  "Jalón en banco plano",
  "Jalón en banco romano",
  "Jalón en multipower",
  "Jalón en máquina",
  "Jalón en polea",
  "Jalón en suelo",
  "Jalón explosivo",
  "Jalón isométrico",
  "Jalón libre",
  "Jalón modificado",
  "Jumping jacks",
  "Jumping jacks a una pierna",
  "Jumping jacks asistido",
  "Jumping jacks con TRX",
  "Jumping jacks con agarre cerrado",
  "Jumping jacks con balón medicinal",
  "Jumping jacks con banda elástica",
  "Jumping jacks con barra",
  "Jumping jacks con mancuernas",
  "Jumping jacks en banco Scott",
  "Jumping jacks en banco inclinado",
  "Jumping jacks en banco plano",
  "Jumping jacks en banco romano",
  "Jumping jacks en multipower",
  "Jumping jacks en máquina",
  "Jumping jacks en polea",
  "Jumping jacks en suelo",
  "Jumping jacks explosivo",
  "Jumping jacks isométrico",
  "Jumping jacks libre",
  "Jumping jacks modificado",
  "Mountain climbers",
  "Mountain climbers a una pierna",
  "Mountain climbers asistido",
  "Mountain climbers con TRX",
  "Mountain climbers con agarre cerrado",
  "Mountain climbers con balón medicinal",
  "Mountain climbers con banda elástica",
  "Mountain climbers con barra",
  "Mountain climbers con mancuernas",
  "Mountain climbers en banco Scott",
  "Mountain climbers en banco inclinado",
  "Mountain climbers en banco plano",
  "Mountain climbers en banco romano",
  "Mountain climbers en multipower",
  "Mountain climbers en máquina",
  "Mountain climbers en polea",
  "Mountain climbers en suelo",
  "Mountain climbers explosivo",
  "Mountain climbers isométrico",
  "Mountain climbers libre",
  "Mountain climbers modificado",
  "Peso muerto",
  "Peso muerto a una pierna",
  "Peso muerto asistido",
  "Peso muerto con TRX",
  "Peso muerto con agarre cerrado",
  "Peso muerto con balón medicinal",
  "Peso muerto con banda elástica",
  "Peso muerto con barra",
  "Peso muerto con mancuernas",
  "Peso muerto en banco Scott",
  "Peso muerto en banco inclinado",
  "Peso muerto en banco plano",
  "Peso muerto en banco romano",
  "Peso muerto en multipower",
  "Peso muerto en máquina",
  "Peso muerto en polea",
  "Peso muerto en suelo",
  "Peso muerto explosivo",
  "Peso muerto isométrico",
  "Peso muerto libre",
  "Peso muerto modificado",
  "Plancha",
  "Plancha a una pierna",
  "Plancha asistido",
  "Plancha con TRX",
  "Plancha con agarre cerrado",
  "Plancha con balón medicinal",
  "Plancha con banda elástica",
  "Plancha con barra",
  "Plancha con mancuernas",
  "Plancha en banco Scott",
  "Plancha en banco inclinado",
  "Plancha en banco plano",
  "Plancha en banco romano",
  "Plancha en multipower",
  "Plancha en máquina",
  "Plancha en polea",
  "Plancha en suelo",
  "Plancha explosivo",
  "Plancha isométrico",
  "Plancha libre",
  "Plancha modificado",
  "Prensa",
  "Prensa a una pierna",
  "Prensa asistido",
  "Prensa con TRX",
  "Prensa con agarre cerrado",
  "Prensa con balón medicinal",
  "Prensa con banda elástica",
  "Prensa con barra",
  "Prensa con mancuernas",
  "Prensa en banco Scott",
  "Prensa en banco inclinado",
  "Prensa en banco plano",
  "Prensa en banco romano",
  "Prensa en multipower",
  "Prensa en máquina",
  "Prensa en polea",
  "Prensa en suelo",
  "Prensa explosivo",
  "Prensa isométrico",
  "Prensa libre",
  "Prensa modificado",
  "Press de banca",
  "Press de banca a una pierna",
  "Press de banca asistido",
  "Press de banca con TRX",
  "Press de banca con agarre cerrado",
  "Press de banca con balón medicinal",
  "Press de banca con banda elástica",
  "Press de banca con barra",
  "Press de banca con mancuernas",
  "Press de banca en banco Scott",
  "Press de banca en banco inclinado",
  "Press de banca en banco plano",
  "Press de banca en banco romano",
  "Press de banca en multipower",
  "Press de banca en máquina",
  "Press de banca en polea",
  "Press de banca en suelo",
  "Press de banca explosivo",
  "Press de banca isométrico",
  "Press de banca libre",
  "Press de banca modificado",
  "Press militar",
  "Press militar a una pierna",
  "Press militar asistido",
  "Press militar con TRX",
  "Press militar con agarre cerrado",
  "Press militar con balón medicinal",
  "Press militar con banda elástica",
  "Press militar con barra",
  "Press militar con mancuernas",
  "Press militar en banco Scott",
  "Press militar en banco inclinado",
  "Press militar en banco plano",
  "Press militar en banco romano",
  "Press militar en multipower",
  "Press militar en máquina",
  "Press militar en polea",
  "Press militar en suelo",
  "Press militar explosivo",
  "Press militar isométrico",
  "Press militar libre",
  "Press militar modificado",
  "Pull-over",
  "Pull-over a una pierna",
  "Pull-over asistido",
  "Pull-over con TRX",
  "Pull-over con agarre cerrado",
  "Pull-over con balón medicinal",
  "Pull-over con banda elástica",
  "Pull-over con barra",
  "Pull-over con mancuernas",
  "Pull-over en banco Scott",
  "Pull-over en banco inclinado",
  "Pull-over en banco plano",
  "Pull-over en banco romano",
  "Pull-over en multipower",
  "Pull-over en máquina",
  "Pull-over en polea",
  "Pull-over en suelo",
  "Pull-over explosivo",
  "Pull-over isométrico",
  "Pull-over libre",
  "Pull-over modificado",
  "Pájaros",
  "Pájaros a una pierna",
  "Pájaros asistido",
  "Pájaros con TRX",
  "Pájaros con agarre cerrado",
  "Pájaros con balón medicinal",
  "Pájaros con banda elástica",
  "Pájaros con barra",
  "Pájaros con mancuernas",
  "Pájaros en banco Scott",
  "Pájaros en banco inclinado",
  "Pájaros en banco plano",
  "Pájaros en banco romano",
  "Pájaros en multipower",
  "Pájaros en máquina",
  "Pájaros en polea",
  "Pájaros en suelo",
  "Pájaros explosivo",
  "Pájaros isométrico",
  "Pájaros libre",
  "Pájaros modificado",
  "Remo",
  "Remo a una pierna",
  "Remo asistido",
  "Remo con TRX",
  "Remo con agarre cerrado",
  "Remo con balón medicinal",
  "Remo con banda elástica",
  "Remo con barra",
  "Remo con mancuernas",
  "Remo en banco Scott",
  "Remo en banco inclinado",
  "Remo en banco plano",
  "Remo en banco romano",
  "Remo en multipower",
  "Remo en máquina",
  "Remo en polea",
  "Remo en suelo",
  "Remo explosivo",
  "Remo isométrico",
  "Remo libre",
  "Remo modificado",
  "Russian twist",
  "Russian twist a una pierna",
  "Russian twist asistido",
  "Russian twist con TRX",
  "Russian twist con agarre cerrado",
  "Russian twist con balón medicinal",
  "Russian twist con banda elástica",
  "Russian twist con barra",
  "Russian twist con mancuernas",
  "Russian twist en banco Scott",
  "Russian twist en banco inclinado",
  "Russian twist en banco plano",
  "Russian twist en banco romano",
  "Russian twist en multipower",
  "Russian twist en máquina",
  "Russian twist en polea",
  "Russian twist en suelo",
  "Russian twist explosivo",
  "Russian twist isométrico",
  "Russian twist libre",
  "Russian twist modificado",
  "Saltar la cuerda",
  "Saltar la cuerda a una pierna",
  "Saltar la cuerda asistido",
  "Saltar la cuerda con TRX",
  "Saltar la cuerda con agarre cerrado",
  "Saltar la cuerda con balón medicinal",
  "Saltar la cuerda con banda elástica",
  "Saltar la cuerda con barra",
  "Saltar la cuerda con mancuernas",
  "Saltar la cuerda en banco Scott",
  "Saltar la cuerda en banco inclinado",
  "Saltar la cuerda en banco plano",
  "Saltar la cuerda en banco romano",
  "Saltar la cuerda en multipower",
  "Saltar la cuerda en máquina",
  "Saltar la cuerda en polea",
  "Saltar la cuerda en suelo",
  "Saltar la cuerda explosivo",
  "Saltar la cuerda isométrico",
  "Saltar la cuerda libre",
  "Saltar la cuerda modificado",
  "Sentadilla",
  "Sentadilla a una pierna",
  "Sentadilla asistido",
  "Sentadilla con TRX",
  "Sentadilla con agarre cerrado",
  "Sentadilla con balón medicinal",
  "Sentadilla con banda elástica",
  "Sentadilla con barra",
  "Sentadilla con mancuernas",
  "Sentadilla en banco Scott",
  "Sentadilla en banco inclinado",
  "Sentadilla en banco plano",
  "Sentadilla en banco romano",
  "Sentadilla en multipower",
  "Sentadilla en máquina",
  "Sentadilla en polea",
  "Sentadilla en suelo",
  "Sentadilla explosivo",
  "Sentadilla isométrico",
  "Sentadilla libre",
  "Sentadilla modificado",
  "Zancadas",
  "Zancadas a una pierna",
  "Zancadas asistido",
  "Zancadas con TRX",
  "Zancadas con agarre cerrado",
  "Zancadas con balón medicinal",
  "Zancadas con banda elástica",
  "Zancadas con barra",
  "Zancadas con mancuernas",
  "Zancadas en banco Scott",
  "Zancadas en banco inclinado",
  "Zancadas en banco plano",
  "Zancadas en banco romano",
  "Zancadas en multipower",
  "Zancadas en máquina",
  "Zancadas en polea",
  "Zancadas en suelo",
  "Zancadas explosivo",
  "Zancadas isométrico",
  "Zancadas libre",
  "Zancadas modificado",
  "Press militar con barra",
"Press militar con mancuernas",
"Press Arnold",
"Elevaciones laterales con mancuernas",
"Elevaciones frontales con mancuernas",
"Elevaciones posteriores en banco inclinado",
"Remo al mentón con barra",
"Press tras nuca",
"Elevaciones laterales con polea",
"Elevaciones laterales inclinadas",
"Press militar en máquina",
"Elevaciones con banda elástica",
"Flexiones pike",
"Flexiones en pino contra pared",
"Push press",
"Dumbbell snatch unilateral",
"Cuban press",
"Face pull con cuerda",
"Elevaciones 90 grados laterales",
"Press Z",
"Sentadilla con barra",
"Sentadilla frontal con barra",
"Sentadilla búlgara",
"Prensa de piernas",
"Zancadas caminando con mancuernas",
"Step-up a banco",
"Sentadilla con salto",
"Extensión de piernas en máquina",
"Wall sit",
"Sentadilla goblet",
"Overhead squat",
"Sentadilla Sissy",
"Zancadas con salto",
"Split squat",
"Lunge con rotación de torso",
"Thruster con barra",
"Jump box squat",
"Skater squat",
"Sentadilla hack en máquina",
"Sentadilla profunda con pausa",
"Peso muerto rumano",
"Peso muerto piernas rígidas",
"Curl femoral en máquina",
"Curl femoral explosivo",
"Curl femoral con fitball",
"Buenos días con barra",
"Desplante hacia atrás",
"Hip hinge con barra",
"Curl nórdico",
"Glute ham raise",
"Flexión femoral con banda",
"Deslizamiento femoral con toalla",
"Curl femoral a una pierna",
"Peso muerto unilateral",
"Sled drag hacia atrás",
"Reverse deadlift",
"Hamstring walkout",
"Isométrico de curl nórdico",
"Curl en banco plano",
"Hamstring curl con TRX",
"Hip thrust",
"Puente de glúteos",
"Patada de glúteo con banda",
"Caminata lateral con banda",
"Peso muerto sumo",
"Step-up con barra",
"Zancada atrás con énfasis en glúteo",
"Sentadilla profunda",
"Elevación pélvica con carga",
"Patada de burro en máquina",
"Curl de muñeca con barra en supinación",
"Curl de muñeca con barra en pronación",
"Curl de muñeca con mancuernas",
"Curl de muñeca inverso con mancuernas",
"Curl martillo",
"Curl inverso con barra",
"Curl Zottman",
"Agarre de pinza con disco",
"Agarre de pinza con mancuerna",
"Agarre con toalla colgando",
"Curl de antebrazo en banco Scott",
"Curl con banda elástica",
"Flexión de muñeca sentado",
"Extensión de muñeca en pronación",
"Agarre colgado en barra fija",
"Agarre con toalla en dominadas",
"Curl de muñeca con polea baja",
"Roller de muñeca con cuerda",
"Agarre tipo pinza con balón medicinal",
"Curl de muñeca con barra Z",
"Elevación de talones de pie",
"Elevación de talones sentado",
"Elevación de talones en máquina Smith",
"Elevación de talones con barra",
"Elevación de talones con mancuernas",
"Elevación de talones en prensa",
"Saltos pliométricos con cuerda",
"Elevaciones de talones en escalón",
"Gemelo en máquina de pie",
"Gemelo sentado en máquina",
"Gemelo en prensa inclinada",
"Gemelo a una pierna con peso",
"Caminar en puntas de pie con mancuernas",
"Gemelo en step a una pierna",
"Gemelo explosivo con salto",
"Farmer walk en puntas de pie",
"Gemelo isométrico en pared",
"Gemelo con banda elástica",
"Gemelo excéntrico en escalón",
"Gemelo tipo burpee jump",
"Dominadas pronas",
"Dominadas supinas",
"Remo con barra",
"Remo con mancuernas",
"Remo en máquina Hammer",
"Remo en polea baja",
"Peso muerto tradicional",
"Peso muerto con piernas rígidas",
"Fondos en paralelas",
"Fondos en banco",
"Extensiones de tríceps acostado con barra",
"Extensiones de tríceps acostado con mancuernas",
"Extensión de tríceps con mancuerna a una mano",
"Patada de tríceps",
"Press francés con barra Z",
"Extensiones de tríceps en polea alta",
"Extensiones con cuerda en polea",
"Press cerrado con barra",
"Flexiones diamante",
"Flexiones con agarre estrecho",
"Extensión de tríceps con banda elástica",
"Extensión de tríceps sentado con mancuerna",
"Patada de tríceps con banda",
"Press de banca con agarre cerrado",
"Extensión de tríceps por detrás de la cabeza",
"Press de tríceps en máquina",
"Fondos con piernas elevadas",
"Extensión de tríceps en polea con barra recta",
"Curl con barra recta",
"Curl con barra Z",
"Curl con mancuernas",
"Curl martillo",
"Curl concentrado",
"Curl en banco Scott",
"Curl en predicador",
"Curl inverso con barra",
"Curl Zottman",
"Curl con polea baja",
"Curl con banda elástica",
"Curl alterno con giro",
"Curl tipo araña (spider curl)",
"Curl de arrastre",
"Curl en banco inclinado",
"Curl en máquina",
"Curl con TRX",
"Curl isométrico",
"Curl doble con mancuernas",
"Curl a una mano en polea",
"Burpees",
"Mountain climbers",
"Jumping jacks",
"Sentadilla con salto",
"Zancadas caminando",
"Peso muerto con mancuerna",
"Step-up a banco",
"Thruster con barra",
"Push press",
"Farmer walk",
"Bear crawl",
"Caminata lateral con banda",
"Swing con kettlebell",
"Clean con mancuernas",
"Snatch con kettlebell",
"Plancha frontal",
"Plancha con toque de hombros",
"Plancha lateral",
"Superman dinámico",
"Dead bug",
"Bird dog",
"Skipping alto",
"Skater jump",
"Box jump",
"Med ball slam",
"Wall ball",
"Flexiones pliométricas",
"Flexiones con desplazamiento lateral",
"TRX row",
"TRX push-up",
"Gateo tipo pantera",
"Plancha con remo",
"Overhead squat",
"Cargada con saco de arena",
"Desplante cruzado con giro",
"Remo renegado",
"Carrera con trineo",
"Battle ropes",
"Cuerda de saltar",
"Sprint en cinta o en calle",
"Desplantes con press por encima de la cabeza",
"Sentadilla + remo con banda elástica",
"Clean and press con mancuernas",
"Zancada con rotación de torso",
"Push-up to row",
"Salto lateral sobre step",
"Caminata de granjero con mancuernas",
"Flexión con palmada",
"Salto al cajón (box jump)",
"Jumping lunge",
"Salto en X",
"Pasos laterales con banda",
"Remo invertido en TRX",
"Press con balón medicinal",
"Balanceo con pesa rusa (kettlebell swing)",
"Elevación de cadera con fitball",
"Ab roll con rueda",
"Plancha con desplazamiento",
"Squat thrust",
"Flexiones con rodilla al codo",
"Zancada en reversa con curl de bíceps",
"Press militar en sentadilla isométrica",
"Plancha con escaladores cruzados",
"Wall sit con balón medicinal",
"Caminata del oso con toque de hombros",
"Agacharse y cargar peso desde el suelo (sandbag lift)",
"Desplante lateral + press frontal",
"Sentadilla + curl + press con mancuernas",
"Carrera corta con cambios de dirección",
"Levantamiento de tronco o saco al hombro",
"Flexiones con mancuernas y rotación",
"Sentadilla con balón medicinal contra la pared",
"Burpee con salto al cajón",
"Cuerda de batalla con sentadilla",
"Desplante con mancuerna y elevación lateral",
"Plancha dinámica en TRX",
"Flexión + giro de tronco",
"Desplante hacia adelante con torsión y disco",
"Press en sentadilla profunda con kettlebell",
"Plancha con pase de disco",
"Sentadilla con desplazamiento lateral",
"Push-up con desplazamiento en círculo",
"Remo con TRX en un solo brazo",
"Flexión con salto de piernas al pecho",
"Flexión con paso lateral de pies",
"Cargada con balón medicinal",
"Salto de rana (frog jump)",
"Escaladores cruzados",
"Sentadilla en equilibrio sobre bosu",
"Sentadilla pistol asistida",
"Jump squat con rodillas al pecho",
"Rotación de torso con balón medicinal",
"Plancha en fitball con extensión de brazos",
"Remo en posición de plancha",
"Desplante lateral con carga frontal",
"Deadlift con mancuerna y rotación",
"Flexión con apoyo en balón medicinal",
"Caminata tipo pantera con kettlebell",
"Press de pecho con banda elástica",
"Abducción de pierna con banda",
"Burpee con rodillas al pecho",
"Zancada adelante y atrás combinada",
"Remo renegado con mancuernas",
"Press con tracción desde posición de sentadilla",
"Sentadilla con balón al pecho + empuje frontal",
"Push-up a T (rotación lateral)",
"Desplante saltado con cambio de brazo",
"Step lateral en bosu",
"Saltos en diagonal sobre conos",
"Snatch con pesa rusa a un brazo",
"Russian twist con balón medicinal",
"Jumping lunge con pausa isométrica",
"Escaladores con slider o toalla",
"Thruster con mancuerna a una mano",
"Flexión pliométrica sobre step",
"Press en sentadilla profunda con banda",
"Caminata del cangrejo con minibanda",
"Remo con cuerda de batalla",



"Pull-over con mancuerna",
"Remo con barra T",
"Jalón al pecho en polea",
"Jalón tras nuca",
"Remo con banda elástica",
"Remo invertido en barra",
"Remo invertido con pies elevados",
"Superman estático",
"Hiperextensiones en banco",
"Good mornings",
"Jalón con agarre neutro",
"Pull-aparts con banda elástica",
"Press de banca con barra",
"Press de banca con mancuernas",
"Press inclinado con barra",
"Press inclinado con mancuernas",
"Press declinado con barra",
"Press declinado con mancuernas",
"Aperturas con mancuernas",
"Aperturas en banco inclinado",
"Aperturas en banco declinado",
"Aperturas en máquina",
"Aperturas con poleas",
"Press en máquina Smith",
"Press en máquina Hammer",
"Fondos para pecho",
"Flexiones tradicionales",
"Flexiones inclinadas",
"Flexiones declinadas",
"Flexiones diamante",
"Flexiones explosivas con aplauso",
"Flexiones con banda elástica",
"Press con mancuernas en el suelo",
"Aperturas con banda elástica",
"Flexiones tipo spiderman",
"Press con kettlebell",
"Aperturas con TRX",
"Flexiones isométricas",
"Press alternado con mancuernas",
"Aperturas con cable cruzado",
"Press con barra en máquina guiada",
"Press con mancuernas en banco reclinable",

"Plancha con pase de disco",
"Sentadilla con desplazamiento lateral",
"Push-up con desplazamiento en círculo",
"Remo con TRX en un solo brazo",
"Flexión con salto de piernas al pecho",
"Flexión con paso lateral de pies",
"Cargada con balón medicinal",
"Salto de rana (frog jump)",
"Escaladores cruzados",
"Sentadilla en equilibrio sobre bosu",
"Sentadilla pistol asistida",
"Jump squat con rodillas al pecho",
"Rotación de torso con balón medicinal",
"Plancha en fitball con extensión de brazos",
"Remo en posición de plancha",
"Desplante lateral con carga frontal",
"Deadlift con mancuerna y rotación",
"Flexión con apoyo en balón medicinal",
"Caminata tipo pantera con kettlebell",
"Press de pecho con banda elástica",
"Abducción de pierna con banda",
"Burpee con rodillas al pecho",
"Zancada adelante y atrás combinada",
"Remo renegado con mancuernas",
"Press con tracción desde posición de sentadilla",
"Sentadilla con balón al pecho + empuje frontal",
"Push-up a T (rotación lateral)",
"Desplante saltado con cambio de brazo",
"Step lateral en bosu",
"Saltos en diagonal sobre conos",
"Snatch con pesa rusa a un brazo",
"Russian twist con balón medicinal",
"Jumping lunge con pausa isométrica",
"Escaladores con slider o toalla",
"Thruster con mancuerna a una mano",
"Flexión pliométrica sobre step",
"Press en sentadilla profunda con banda",
"Caminata del cangrejo con minibanda",
"Remo con cuerda de batalla",



  ];

  input.parentElement.style.position = "relative";
    input.parentElement.appendChild(sugerencias);

    input.addEventListener("input", () => {
      const valor = input.value.toLowerCase().trim();
      sugerencias.innerHTML = "";

      if (valor.length < 2) {
        sugerencias.style.display = "none";
        return;
      }

      function quitarAcentos(texto) {
  return texto.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

const coincidencias = listaEjercicios
  .filter(ej => {
    const sinAcentos = quitarAcentos(ej.toLowerCase());
    const palabras = sinAcentos.split(" ");
    const valorSinAcentos = quitarAcentos(valor);
    return palabras.some(palabra => palabra.includes(valorSinAcentos));
  })
  .slice(0, 200);


      if (coincidencias.length === 0) {
        sugerencias.style.display = "none";
        return;
      }

      coincidencias.forEach(nombre => {
        const li = document.createElement("li");
        li.textContent = nombre;
        Object.assign(li.style, {
          padding: "8px",
          cursor: "pointer"
        });
        li.addEventListener("click", () => {
          input.value = nombre;
          sugerencias.style.display = "none";
        });
        sugerencias.appendChild(li);
      });

      sugerencias.style.display = "block";
    });

    document.addEventListener("click", (e) => {
      if (!sugerencias.contains(e.target) && e.target !== input) {
        sugerencias.style.display = "none";
      }
    });
  });
